# map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

footprint: [ [-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1] ]

transform_tolerance: 1.0

# robot_radius: 0.25
inflation_radius: 0.35

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar_1, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
